// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package mod.upcraftlp.peachdudes.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPeachDude extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Stalk;
    ModelRenderer LeafBody;
    ModelRenderer LeafTip;
  
  public ModelPeachDude()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 6, 6, 6);
      Body.setRotationPoint(-3F, 18F, -3F);
      Body.setTextureSize(32, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Stalk = new ModelRenderer(this, 12, 12);
      Stalk.addBox(2.5F, -1F, 2.5F, 1, 1, 1);
      Stalk.setRotationPoint(-3F, 18F, -3F);
      Stalk.setTextureSize(32, 32);
      Stalk.mirror = true;
      setRotation(Stalk, 0F, 0F, 0F);
      LeafBody = new ModelRenderer(this, 0, 12);
      LeafBody.addBox(1.5F, -1F, -0.5F, 3, 0, 3);
      LeafBody.setRotationPoint(-1F, 18F, -1F);
      LeafBody.setTextureSize(32, 32);
      LeafBody.mirror = true;
      setRotation(LeafBody, 0F, 0F, 0F);
      LeafTip = new ModelRenderer(this, 3, 12);
      LeafTip.addBox(2.5F, -1F, -1.5F, 1, 0, 1);
      LeafTip.setRotationPoint(1F, 18F, 1F);
      LeafTip.setTextureSize(32, 32);
      LeafTip.mirror = true;
      setRotation(LeafTip, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    Stalk.render(f5);
    LeafBody.render(f5);
    LeafTip.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
